### ISSUE TITLE
No indications on which items contain subitems, and which do not

### ISSUE THREAD

**Issue by rvion** [Globidev/term-picker#1]
![image](https://cloud.githubusercontent.com/assets/2150990/8157206/03f82438-1353-11e5-8933-716d27235d49.png)

here, in pannel 3, we don't know we can open item 2

**Comment by Globidev** [comment]
Yep you're right.
It can be easily done but I need design advice though

Maybe using `+`/`-` ? color ? I wish I was an artist :cry:

**Comment by rvion** [comment]
proposition:
- [ ] add /.. suffix 

```
|--item1
|--item2/..
|--item3
```
- [ ] open element on enter key (because if feels like a :bug: otherwise)
- [ ] add number of subelements in parenthesis :question: 

```
|--item1
|--item2/.. (1)
|--item3
```

**Comment by Globidev** [comment]
The return key is already bound to select an item
I may bind it to expand a node if the `--leaf-selection` flag is set
What do you think ?

**Comment by rvion** [comment]
I think return key should both `open file` on leaf and  `open folder + go to first child` on folder.
because this is the default behaviour on mac, windos, linux tree gui

**Comment by rvion** [comment]
Oh, you mean we can select a folder right now ?
I think --folder-selection should be the option to add, with a default on just being able to select leaves

**Comment by Globidev** [comment]
This tool is not restricted to file/directories
Speaking about opening files and _folders_ (which is a bad Windows term btw) is not really consistent with the mindset of this project
In term of default options, I think it's just not worth spending time on trying to figure out what the common use cases are. Targeted users will be shell users and should be capable of aliasing `pick` to `pick -l` if they find it more convenient. I rather implement options in term of specialization.

**Comment by Globidev** [comment]
Deployed on duckerhub :whale:

**Comment by rvion** [comment]
:green_heart: 

I understand, but still am not convinced.
I no longer have a strong opinion, but still, here are some arguments for both side.
1. All use-cases I can think of use leaves-selection only (files, compose command by visually selecting flags of an app ,etc).
2. if we can select folder, what is then the action of pressing left arrow on a leaf ?
3. Leaves and Nodes do not have the same type, so it feels weird to select an array of `Either Leaf Node`. I understand this is biased on words (Leaves and Nodes) but fact is they have different semantics.
4. On linux, doing ls -la shows `.`, and `..` as children of current directory, so one could select `.` insead of selecting the node.
5. Robin, Fabrice, I thought pressing enter on a node was going to open the node
6. Some trees are defined as `Tree a = Node [Tree] | Leaf a`, some as `Tree a = Node a [Tree] | Leaf a`
7. is selecting a folder as you want with an other key so illogical ? (like ctrl-enter)
8. What even means selecting a folder ? selecting all of its first level children ? Selecting all of it's children AND sub-children ? Selecting fodler only ?
9. Why would you not include the '/' at the end when selecting a folder in produced output? lots of tools need it, and as of now, term-picker can't.
10. URIs with '/' denotes folder encapsulation, and you train the user to think so since you ask him to 
11. I'm against changing behaviour via a flag. it goes against ergonomics. All options should be possible without collision I think.

random thought:
one could emulate selecting all sub-elements in a file selection scenario via params like
  node/*
  node/**

I think I still an in favor of enter key opens node (and do not selecting it), with an extra shortcur or two to select folder (with `/` and without)
At least, if you decide against, I really advice against having a flag to change GUI behaviour with possible key collistion.

**Comment by Globidev** [comment]
Why is it still about directories (#folders). Never meant the app to be about that
Words Haskell bla bla :kappa:

> At least, if you decide against

I don't, It does make sense when `leaf-selection` is active
implemented above in @b623619

> 1. if we can select folder, what is then the action of pressing left arrow on a leaf ?

you mean right arrow ?

> 1. Leaves and Nodes do not have the same type

They do here

> 1. Robin, Fabrice, I thought pressing enter on a node was going to open the node

Well, everyone will be happy now

> 1. Some trees are defined as Tree a = Node [Tree] | Leaf a, some as Tree a = Node a [Tree] | Leaf a

I did not implement a recursive data-type sorry, must be bad design D: #functionalprogramming

> 7.
> 8.

#foldertalk

> 1. Why would you not include the '/' at the end when selecting a folder in produced output? lots of tools need it, and as of now, term-picker can't.

again, very specific. The separator is not necessary a '/' btw
Why not just echo a `/` or, even better, send mails of insults to the developers of the tools in question?

> 1. URIs with '/' denotes folder encapsulation, and you train the user to think so since you ask him to

What did I ask him ?

> 1. I'm against changing behaviour via a flag. it goes against ergonomics. All options should be possible without collision I think.

It's hard to make a terminal app `ergonomic`, especially since people just use their mice. It's even harder to develop an ergonomic terminal app (terminal emulators are not that great and ncurses is :shit:). Plus, I think the lifespan of an instance of this app tends to be short, it doesn't need fancy key-binding and modes like vim. Managing behaviour with flags seems to be the easier option

**Comment by rvion** [comment]
I was just trying to give ideas to let us think about stuff. No strong opinion, sorry to have annoyed you with all this those folders talk.

**Comment by rvion** [comment]
btw, did you see my smses I sent after previous comment?

**Comment by Globidev** [comment]
I did

**Comment by Globidev** [comment]
Glad we are talking about it on a public github repo
I feel like a drama queen :dancer:

**Comment by rvion** [comment]
so let's delete them :)

**Comment by Globidev** [comment]
Github employees can still laugh at us :frowning:

**Comment by rvion** [comment]
btw, you stole my drama dancing queen

**Comment by Globidev** [comment]
you didn't patent it, too bad :smiling_imp:
