### ISSUE TITLE
License file ?

### ISSUE THREAD

**Issue by rvion** [Globidev/term-picker#3]
I have a few questions regarding your tool:
- What is the license ? 
- I would like to suggest other people to start using your tool because it's just awesome. Can I do so ?
- Can someone/an organisation host a copy of your image in his personnal docker registry ?

**Comment by rvion** [comment]
when there is no license like now, this applies: https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

more generally, this is good read: https://help.github.com/articles/open-source-licensing

**Comment by Globidev** [comment]
> What is the license ?

Calling my lawyer BRB

> I would like to suggest other people to start using your tool because it's just awesome. Can I do so ?

:blush: 

> Can someone/an organisation host a copy of your image in his personnal docker registry ?

I don't see why not

**Comment by Globidev** [comment]
Added a MIT licence in @97d66d5c64508535be93de4ec72afb4f85907192

**Comment by rvion** [comment]
:meat_on_bone: license for the win :poultry_leg:
